const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

function sqlEscape(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
}

function normalizeKey(s) {
  return String(s ?? '')
    .replace(/\s+/g, ' ')
    .trim();
}

function deptCodeFromName(name) {
  // Deterministic short code to satisfy NOT NULL + UNIQUE(code).
  // Uses a stable hash; collisions are extremely unlikely.
  const h = crypto.createHash('sha1').update(String(name)).digest('hex').slice(0, 10).toUpperCase();
  return `D${h}`;
}

function parseDateDDMonYYYY(s) {
  // staffinfo.json uses e.g. "1 Jan 2026"
  const v = normalizeKey(s);
  if (!v) return null;
  const m = v.match(/^(\d{1,2})\s+([A-Za-z]{3})\s+(\d{4})$/);
  if (!m) return null;
  const day = Number(m[1]);
  const mon = m[2].toLowerCase();
  const year = Number(m[3]);
  const months = {
    jan: 1, feb: 2, mar: 3, apr: 4, may: 5, jun: 6,
    jul: 7, aug: 8, sep: 9, oct: 10, nov: 11, dec: 12,
  };
  const month = months[mon];
  if (!month || !day || !year) return null;
  const mm = String(month).padStart(2, '0');
  const dd = String(day).padStart(2, '0');
  return `${year}-${mm}-${dd}`;
}

function main() {
  const staffInfoPath = path.resolve(__dirname, '../public/staffinfo.json');
  const raw = fs.readFileSync(staffInfoPath, 'utf8');
  const rows = JSON.parse(raw);

  // Build unique departments and their parents from Dept / Parent Dept
  const parentNames = new Set();
  const deptToParent = new Map(); // dept -> parent (or null)

  for (const r of rows) {
    const dept = normalizeKey(r['Dept'] || r['Department']);
    const parent = normalizeKey(r['Parent Dept'] || r['Parent Dept '] || r['Parent'] || r['Parent Department']);
    if (!dept) continue;
    if (!parent || parent === dept) {
      parentNames.add(dept);
      if (!deptToParent.has(dept)) deptToParent.set(dept, null);
    } else {
      parentNames.add(parent);
      deptToParent.set(dept, parent);
    }
  }

  // Determine which nodes are "parents" vs "children"
  const allNames = new Set([...parentNames, ...deptToParent.keys()]);
  const parentList = [...parentNames].sort((a, b) => a.localeCompare(b));
  const childList = [...deptToParent.entries()]
    .filter(([, p]) => p !== null)
    .map(([d, p]) => ({ dept: d, parent: p }))
    .sort((a, b) => (a.parent + '|' + a.dept).localeCompare(b.parent + '|' + b.dept));

  // Generate SQL
  let out = '';
  out += '-- Generated by scripts/import_staffinfo.js\n';
  out += `-- Source: public/staffinfo.json (${rows.length} staff rows)\n\n`;

  out += 'START TRANSACTION;\n\n';

  out += '-- 1) Optional: extend users table to store staffinfo fields\n';
  out += `ALTER TABLE users
  ADD COLUMN IF NOT EXISTS surname VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS first_name VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS other_names VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS contract_terms VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS contract_type VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS staff_category VARCHAR(80) NULL;\n\n`;

  out += '-- 2) Rebuild departments from staffinfo Dept / Parent Dept\n';
  out += '-- IMPORTANT: this deletes current departments. Ensure nothing critical depends on existing IDs.\n';
  out += 'SET FOREIGN_KEY_CHECKS=0;\n';
  out += 'DELETE FROM departments;\n';
  out += 'SET FOREIGN_KEY_CHECKS=1;\n\n';

  out += '-- Insert parent departments/offices/faculties (parent_id = NULL)\n';
  out += 'INSERT INTO departments (name, code, unit_type, parent_id, hod_id, is_active, description, created_at, external_name)\nVALUES\n';
  out += parentList
    .map((name) => {
      const code = deptCodeFromName(name);
      return `  (${sqlEscape(name)}, ${sqlEscape(code)}, 'office', NULL, NULL, 1, NULL, CURRENT_TIMESTAMP, ${sqlEscape(name)})`;
    })
    .join(',\n');
  out += ';\n\n';

  out += '-- Insert child departments/units (parent_id resolved by external_name)\n';
  out += 'INSERT INTO departments (name, code, unit_type, parent_id, hod_id, is_active, description, created_at, external_name)\nVALUES\n';
  out += childList
    .map(({ dept, parent }) => {
      const code = deptCodeFromName(`${parent}::${dept}`);
      return `  (${sqlEscape(dept)}, ${sqlEscape(code)}, 'department', (SELECT id FROM departments WHERE external_name=${sqlEscape(parent)} LIMIT 1), NULL, 1, NULL, CURRENT_TIMESTAMP, ${sqlEscape(dept)})`;
    })
    .join(',\n');
  out += ';\n\n';

  out += '-- 3) Upsert users by email; set department_id by Dept mapping\n';
  out += '-- NOTE: This creates placeholder accounts (password_hash="imported") for any email not already in users.\n';
  out += 'INSERT INTO users (full_name, email, password_hash, role, department_id, position, contract_start_date, contract_end_date, surname, first_name, other_names, contract_terms, contract_type, staff_category, status, employment_status, leave_status, must_change_password)\nVALUES\n';

  const byEmail = new Map();
  for (const r of rows) {
    const email = normalizeKey(r['Email']).toLowerCase();
    if (!email) continue;
    // Keep first occurrence per email (avoid duplicates)
    if (byEmail.has(email)) continue;

    const fullName = normalizeKey(r['Name']) || [r['First Name'], r['Othernames'], r['Surname']].filter(Boolean).join(' ');
    const dept = normalizeKey(r['Dept'] || r['Department']);
    const position = normalizeKey(r['Position']);
    const start = parseDateDDMonYYYY(r['Contract Starts']);
    const end = parseDateDDMonYYYY(r['Contract Ends']);

    byEmail.set(email, {
      fullName,
      email,
      dept,
      position,
      start,
      end,
      surname: normalizeKey(r['Surname']),
      firstName: normalizeKey(r['First Name']),
      otherNames: normalizeKey(r['Othernames']),
      contractTerms: normalizeKey(r['Contract Terms']),
      contractType: normalizeKey(r['Contract Type']),
      category: normalizeKey(r['Category']),
    });
  }

  const usersList = [...byEmail.values()].sort((a, b) => a.email.localeCompare(b.email));
  out += usersList
    .map((u) => {
      return `  (${sqlEscape(u.fullName)}, ${sqlEscape(u.email)}, ${sqlEscape('imported')}, ${sqlEscape('staff')}, (SELECT id FROM departments WHERE external_name=${sqlEscape(u.dept)} LIMIT 1), ${sqlEscape(u.position || null)}, ${sqlEscape(u.start)}, ${sqlEscape(u.end)}, ${sqlEscape(u.surname || null)}, ${sqlEscape(u.firstName || null)}, ${sqlEscape(u.otherNames || null)}, ${sqlEscape(u.contractTerms || null)}, ${sqlEscape(u.contractType || null)}, ${sqlEscape(u.category || null)}, 'Pending', 'active', 'On Duty', 1)`;
    })
    .join(',\n');
  out += '\nON DUPLICATE KEY UPDATE\n';
  out += '  full_name=VALUES(full_name),\n';
  out += '  department_id=VALUES(department_id),\n';
  out += '  position=COALESCE(VALUES(position), position),\n';
  out += '  contract_start_date=COALESCE(VALUES(contract_start_date), contract_start_date),\n';
  out += '  contract_end_date=COALESCE(VALUES(contract_end_date), contract_end_date),\n';
  out += '  surname=COALESCE(VALUES(surname), surname),\n';
  out += '  first_name=COALESCE(VALUES(first_name), first_name),\n';
  out += '  other_names=COALESCE(VALUES(other_names), other_names),\n';
  out += '  contract_terms=COALESCE(VALUES(contract_terms), contract_terms),\n';
  out += '  contract_type=COALESCE(VALUES(contract_type), contract_type),\n';
  out += '  staff_category=COALESCE(VALUES(staff_category), staff_category);\n\n';

  out += 'COMMIT;\n';

  const outPath = path.resolve(__dirname, '../public/staffinfo_import.sql');
  fs.writeFileSync(outPath, out, 'utf8');
  console.log(`Wrote ${outPath}`);
  console.log(`Departments: ${allNames.size} (parents: ${parentList.length}, children: ${childList.length})`);
  console.log(`Users upserted by email: ${usersList.length}`);
}

main();

